name: FrontEnd Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        run: |
          echo ${{ secrets.AWS_ACCESS_KEY_ID }} > aws_access_key_id
          echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} > aws_secret_access_key
          aws configure set aws_access_key_id $(cat aws_access_key_id)
          aws configure set aws_secret_access_key $(cat aws_secret_access_key)
          aws configure set aws_region ${{ secrets.AWS_REGION }}
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        shell: bash

      - name: S3 Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: aws s3 sync . s3://${{ secrets.AWS_BUCKET }}/ --acl bucket-owner-full-control

  
