name: FrontEnd Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        run: |
          echo ${{ AWS_ACCESS_KEY_ID }} > aws_access_key_id
          echo ${{ AWS_SECRET_ACCESS_KEY }} > aws_secret_access_key
          aws configure set aws_access_key_id $(cat aws_access_key_id)
          aws configure set aws_secret_access_key $(cat aws_secret_access_key)
          aws configure set aws_region ${{ AWS_REGION }}
        env:
          AWS_DEFAULT_REGION: ${{ AWS_REGION }}
        shell: bash

      - name: S3 Deploy
        run: aws s3 sync ./dist s3://adme-buckets/ --acl bucket-owner-full-control
