name: FrontEnd Deploy

on:
  push:
    branches: [ main ]


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install
        
      - name: Build
        run: yar build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ AWS_REGION }}

      - name: S3 Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ AWS_REGION }}
        run:
          aws s3 sync ./dist s3://adme-buckets/ --acl bucket-owner-full-control
